# Generated by Django 6.0.3 on 2026-03-17 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carvideo',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
    ]
