# Generated by Django 6.0.3 on 2026-03-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='airbags',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Jeep', 'Jeep'), ('Pickup', 'Pickup'), ('Minivan', 'Minivan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('silver', 'Silver'), ('grey', 'Grey'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('brown', 'Brown'), ('golden', 'Golden'), ('beige', 'Beige'), ('maroon', 'Maroon'), ('purple', 'Purple'), ('Carnelian red', 'Carnelian red')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('2-Mar', '2-Mar'), ('4-May', '4-May'), ('>5', '>5')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_wheels',
            field=models.CharField(choices=[('Front', 'Front'), ('4x4', '4x4'), ('Rear', 'Rear')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('LPG', 'LPG'), ('Hydrogen', 'Hydrogen')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='gear_box_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('Variator', 'Variator'), ('Tiptronic', 'Tiptronic')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='leather_interior',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='wheel',
            field=models.CharField(choices=[('Left wheel', 'Left wheel'), ('Right-hand drive', 'Right-hand drive')], max_length=30),
        ),
    ]
