# Generated by Django 6.0.3 on 2026-05-08 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('jeep', 'Jeep'), ('pickup', 'Pickup'), ('minivan', 'Minivan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('silver', 'Silver'), ('grey', 'Grey'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('brown', 'Brown'), ('golden', 'Golden'), ('beige', 'Beige'), ('maroon', 'Maroon'), ('purple', 'Purple'), ('carnelian red', 'Carnelian red')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('2-mar', '2-Mar'), ('4-may', '4-May'), ('>5', '>5')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_wheels',
            field=models.CharField(choices=[('front', 'Front'), ('4x4', '4x4'), ('rear', 'Rear')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('lpg', 'LPG'), ('hydrogen', 'Hydrogen')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='gear_box_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('variator', 'Variator'), ('tiptronic', 'Tiptronic')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='leather_interior',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='wheel',
            field=models.CharField(choices=[('left wheel', 'Left wheel'), ('right-hand drive', 'Right-hand drive')], max_length=30),
        ),
        migrations.CreateModel(
            name='CarPricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lower_price_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('upper_price_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('seller_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_status', models.CharField(choices=[('low', 'Low Price'), ('regular', 'Regular Price'), ('high', 'High Price'), ('insufficient_data', 'Insufficient Data')], default='insufficient_data', max_length=30)),
                ('model_mae', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('model_r2_score', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('model_mape', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_prediction', to='cars.car')),
            ],
        ),
    ]
