# Generated by Django 6.0.3 on 2026-05-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_category_alter_car_color_alter_car_doors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='levy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
