# Generated by Django 6.0.3 on 2026-05-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
